language: node_js

node_js:
  - "4"
  - "stable"

install:
  - npm install

script:
  - npm run build
  - npm test

after_success:
  - npm run coveralls
  - npm run codecov

notifications:
  email: false
